menus:
  guides:
    - title: '_Boundaries'
      state: 'settings.show_boundaries'
      event: 'toggle-constellations-boundaries'
    - title: '_Asterisms'
      state: 'settings.show_asterisms'
      event: 'toggle-asterisms'

  grids:
    - title: '_Equatorial'
      state: 'settings.show_equatorial_grid'
      event: 'toggle-equatorial-grid'
    - title: 'E_cliptic'
      state: 'settings.show_ecliptic_grid'
      event: 'toggle-ecliptic-grid'

  stereo:
    - title: 'Hardware support'
      state: 'settings.stereoscopic_framebuffer'
      event: 'toggle-stereoscopic-framebuffer'
    - title: 'Red-Blue'
      state: 'settings.red_blue_stereo'
      event: 'toggle-red_blue-stereo'
    - title: 'Side by side'
      state: 'settings.side_by_side_stereo'
      event: 'toggle-side-by_side-stereo'
    - title: 'Swap eyes'
      state: 'settings.stereo_swap_eyes'
      event: 'toggle-swap-eyes'

menubar:
- title: '_Cosmonium'
  entries:
    - title: '_Find object'
      event: 'gui-search-object'
    -
    - title: '_Save URL'
      event: 'save-cel-url'
    - title: '_Load URL'
      event: 'load-cel-url'
    -
    - title: 'Load _CEL script'
      event: 'open-script'
    -
    - title: 'Go to _home'
      event: 'select-home'
    -
    - title: '_Preferences'
      event: 'gui-show-preferences'
    -
    - title: '_Quit'
      event: 'exit'

- title: '_Select'
  entries:
    - title: '_Info'
      event: 'gui-show-info'
      enabled: 'engine.selected'
    - title: '_Edit'
      event: 'gui-show-editor'
      enabled: 'engine.selected'
    - title: "More info"
      menu: extra-info
      enabled: 'engine.selected'
    -
    - title: '_Go to'
      event: 'goto-selected'
      enabled: 'engine.selected'
    - title: 'Go to f_ront'
      event: 'goto-front'
      enabled: 'engine.selected'
    - title: 'Go to _surface'
      event: 'goto-surface'
      enabled: 'engine.selected'
    -
    - title: '_Follow'
      event: 'follow-selected'
      enabled: 'engine.selected'
    - title: 'S_ync'
      event: 'sync-selected'
      enabled: 'engine.selected'
    -
    - title: '_Reset navigation'
      event: 'cancel'
      enabled: 'engine.selected'
    -
    - title: "Orbiting bodies"
      menu: 'orbiting-bodies'
      enabled: 'engine.selected'
    - title: "Orbits"
      menu: 'orbits'
      enabled: 'engine.selected'

- title: '_Time'
  entries:
    - title: '_Increase rate 10x'
      event: 'accelerate-time-10'
    - title: 'I_ncrease rate 2x'
      event: 'accelerate-time-2'
    - title: '_Decrease rate 10x'
      event: 'slow-time-10'
    - title: 'D_ecrease rate 2x'
      event: 'slow-time-2'
    - title: '_Reverse time'
      event: 'invert-time'
    - title: '_Freeze time'
      event: 'toggle-freeze-time'
    - title: '_Set real time'
      event: 'set-real-time'
    -
    - title: 'Set _time...'
      event: 'gui-show-time-editor'
    - title: 'Set _current time'
      event: 'set-current-date'
    - title: 'Set _J2000 epoch'
      event: 'set-j2000-date'

- title: 'Camera'
  entries:
    - title: '_Mode'
      menu: 'select-camera-controller'
    -
    - title: '_Center on'
      event: 'center-selected'
      enabled: 'engine.selected'
    #- title: 'Look _back'
    #  event: camera-look-back
    - title: '_Track'
      event: 'track-selected'
      enabled: 'engine.selected'
    -
    - title: 'Zoom _in'
      event: 'zoom-in'
    - title: 'Zoom _out'
      event: 'zoom-out'
    - title: '_Reset Zoom'
      event: 'reset-zoom'
    -
    - title: '_Select ship'
      menu: 'select-ship'
    - title: '_Edit ship'
      event: 'gui-show-ship-editor'
      enabled: 'engine.ship.editable'

- title: '_Render'
  entries:
    - title: '_Labels'
      entries:
        - title: '_Galaxies'
          state: 'labels.is_shown("galaxy")'
          event: 'toggle-label-galaxy'
        #- title: 'Globular'
        #  state: 'labels.is_shown("globular")'
        #  event: 'toggle-label-globular'
        - title: '_Stars'
          state: 'labels.is_shown("star")'
          event: 'toggle-label-star'
        - title: '_Planets'
          state: 'labels.is_shown("planet")'
          event: 'toggle-label-planet'
        - title: '_Dwarf planets'
          state: 'labels.is_shown("dwarfplanet")'
          event: 'toggle-label-dwarfplanet'
        - title: '_Moons'
          state: 'labels.is_shown("moon")'
          event: 'toggle-label-moon'
        - title: 'M_inor Moons'
          state: 'labels.is_shown("minormoon")'
          event: 'toggle-label-minormoon'
        - title: 'L_ost Moons'
          state: 'labels.is_shown("lostmoon")'
          event: 'toggle-label-lostmoon'
        - title: 'C_omets'
          state: 'labels.is_shown("comet")'
          event: 'toggle-label-comet'
        - title: '_Asteroids'
          state: 'labels.is_shown("asteroid")'
          event: 'toggle-label-asteroid'
        - title: 'I_nterstellars'
          state: 'labels.is_shown("interstellar")'
          event: 'toggle-label-interstellar'
        - title: 'S_pacecrafts'
          state: 'labels.is_shown("spacecraft")'
          event: 'toggle-label-spacecraft'
        - title: '_Constellations'
          state: 'labels.is_shown("constellation")'
          event: 'toggle-label-constellation'
        #- title: 'Locations'
        #  state: 'label-location'
        #  event: 'toggl-label-location'
    - title: '_Orbits'
      entries:
        - title: 'All _orbits'
          state: 'settings.show_orbits'
          event: 'toggle-orbits'
        -
        - title: '_Stars'
          state: 'orbits.is_shown("star")'
          event: 'toggle-orbit-star'
        - title: '_Planets'
          state: 'orbits.is_shown("planet")'
          event: 'toggle-orbit-planet'
        - title: '_Dwarf planets'
          state: 'orbits.is_shown("dwarfplanet")'
          event: 'toggle-orbit-dwarfplanet'
        - title: '_Moons'
          state: 'orbits.is_shown("moon")'
          event: 'toggle-orbit-moon'
        - title: 'M_inor moons'
          state: 'orbits.is_shown("minormoon")'
          event: 'toggle-orbit-minormoon'
        - title: 'L_ost moons'
          state: 'orbits.is_shown("lostmoon")'
          event: 'toggle-orbit-lostmoon'
        - title: '_Comets'
          state: 'orbits.is_shown("comet")'
          event: 'toggle-orbit-comet'
        - title: '_Asteroids'
          state: 'orbits.is_shown("asteroid")'
          event: 'toggle-orbit-asteroid'
        - title: 'I_nterstellars'
          state: 'orbits.is_shown("interstellar")'
          event: 'toggle-orbit-interstellar'
        - title: 'S_pacecrafts'
          state: 'orbits.is_shown("spacecraft")'
          event: 'toggle-orbit-spacecraft'
    - title: '_Bodies'
      entries:
        - title: '_Galaxies'
          state: 'bodies.is_shown("galaxy")'
          event: 'toggle-body-class-galaxy'
    - title: 'O_ptions'
      entries:
        - title: '_Atmospheres'
          state: 'settings.show_atmospheres'
          event: 'toggle-atmosphere'
        - title: '_Clouds'
          state: 'settings.show_clouds'
          event: 'toggle-clouds'
          #- title: 'Shadows'
          #  event: 'toggle-shadows'
          #- title: 'Night sides'
          #  event: 'toggle-nightsides'
          #- title: 'Comet tails'
          #  event: 'toggle-comet-tails'
    - title: '_Grids'
      menu: grids
    - title: 'G_uides'
      menu: guides
    - title: '_3D'
      menu: stereo
    - title: '_Advanced'
      entries:
        - title: '_Decrease ambient'
          event: 'decrease-ambient'
        - title: '_Increase ambient'
          event: 'increase-ambient'
        -
        - title: 'Fewer _Stars Visible'
          event: 'decrease-limit-magnitude'
        - title: '_More Stars Visible'
          event: 'increase-limit-magnitude'
        -
        - title: '_Rotation axis'
          state: 'settings.show_rotation_axis'
          event: 'toggle-rotation-axis'
        - title: 'Reference _frame'
          state: 'settings.show_reference_axis'
          event: 'toggle-reference-axis'

- title: '_Window'
  entries:
    - title: 'Toggle _fullscreen'
      event: 'toggle-fullscreen'
    - title: 'Toggle _menubar'
      event: 'gui-toggle-menubar'
    - title: 'Toggle _HUD'
      event: 'toggle-hud'
    -
    - title: 'Save _screenshot'
      event: 'save-screenshot'
    - title: 'Save screenshot _without UI'
      event: 'save-screenshot-no-gui'
    - title: 'Set screenshots directory...'
      event: 'gui-show-select-screenshots'

- title: '_Debug'
  entries:
    - title: 'Toggle filled wireframe'
      event: 'debug-toggle-filled-wireframe'
    - title: 'Toggle wireframe'
      event: 'debug-toggle-wireframe'
    - title: "Show render buffers"
      event: 'debug-toggle-buffer-viewer'
    - title: 'Show shadow frustum'
      state: 'settings.debug_shadow_frustum'
      event: 'debug-toggle-shadows-frustum'
    -
    - title: 'Shaders'
      entries:
        - title: 'Default'
          state: 'settings.shader_debug_fragment_shader == "default"'
          event: 'debug-shader-fragment-mode-default'
        - title: 'Diffuse'
          state: 'settings.shader_debug_fragment_shader == "diffuse"'
          event: 'debug-shader-fragment-mode-diffuse'
        - title: 'Normals'
          state: 'settings.shader_debug_fragment_shader == "normal"'
          event: 'debug-shader-fragment-mode-normal'
        - title: 'Normal map'
          state: 'settings.shader_debug_fragment_shader == "normalmap"'
          event: 'debug-shader-fragment-mode-normalmap'
        - title: 'Shadows'
          state: 'settings.shader_debug_fragment_shader == "shadows"'
          event: 'debug-shader-fragment-mode-shadows'
        - title: 'Heightmap'
          state: 'settings.shader_debug_fragment_shader == "heightmap"'
          event: 'debug-shader-fragment-mode-heightmap'
        - title: 'Color picking'
          state: 'settings.shader_debug_fragment_shader == "picking"'
          event: 'debug-shader-fragment-mode-picking'
        - title: 'Ray hit'
          state: 'settings.shader_debug_raymarching_canvas'
          event: 'debug-toggle-shader-raymarching-canvas'
        - title: 'Show slice'
          state: 'settings.shader_debug_raymarching_slice'
          event: 'debug-toggle-shader-debug-raymarching_slice'
    - title: 'Instant movement'
      state: 'settings.debug_jump'
      event: 'debug-toggle-jump'
    - title: 'Connect pstats'
      event: 'debug-connect-pstats'
    - title: 'Render info'
      entries:
        - title: 'Frame per second'
          state: 'settings.display_render_info == "fps"'
          event: 'set-display-render-info-fps'
        - title: 'Render time'
          state: 'settings.display_render_info == "ms"'
          event: 'set-display-render-info-ms'
        - title: 'None'
          state: 'settings.display_render_info == None'
          event: 'set-display-render-info-none'
    -
    - title: 'Freeze LOD'
      state: 'settings.debug_lod_freeze'
      event: 'debug-freeze-lod'
    - title: 'Dump LOD stats'
      event: 'debug-dump-objects-stats'
    - title: 'Dump LOD tree'
      event: 'debug-dump-objects-info'
    - title: 'Log LOD events'
      state: 'settings.debug_lod_split_merge'
      event: 'debug-toggle-split-merge-log'
    - title: 'Show boundaries'
      state: 'settings.shader_debug_coord'
      event: 'debug-toggle-shader-debug-coord'
    - title: 'Show LOD bounding boxes'
      state: 'settings.debug_lod_show_bb'
      event: 'debug-toggle-bounding-boxes'
    - title: 'Show LOD culling frustum'
      state: 'settings.debug_lod_frustum'
      event: 'debug-toggle-lod-frustum'
    -
    - title: 'Show octree stats'
      event: 'debug-dump-octree-stats'
    - title: 'Dump octree'
      event: 'debug-dump-octree'

- title: '_Help'
  entries:
    - title: 'User _guide'
      event: 'gui-show-help'
    -
    - title: '_Credits'
      event: 0
    - title: '_License'
      event: 'gui-show-license'
    -
    - title: '_About'
      event: 'gui-show-about'
