menus:
  guides:
    - title: '_Boundaries'
      state: 'show-boundaries'
      event: 'toggle-constellations-boundaries'
    - title: '_Asterisms'
      state: 'show-asterisms'
      event: 'toggle-asterisms'

  grids:
    - title: '_Equatorial'
      state: 'show-equatorial-grid'
      event: 'toggle-equatorial-grid'
    - title: 'E_cliptic'
      state: 'show-ecliptic-grid'
      event: 'toggle-ecliptic-grid'

  stereo:
    - title: 'Hardware support'
      state: 'stereoscopic-framebuffer'
      event: 'toggle-stereoscopic-framebuffer'
    - title: 'Red-Blue'
      state: 'red-blue-stereo'
      event: 'toggle-red_blue-stereo'
    - title: 'Side by side'
      state: 'side-by-side-stereo'
      event: 'toggle-side-by_side-stereo'
    - title: 'Swap eyes'
      state: 'stereo-swap-eyes'
      event: 'toggle-swap-eyes'

menubar:
- title: '_Cosmonium'
  entries:
    - title: '_Find object'
      event: 'gui-search-object'
    -
    - title: '_Save URL'
      event: 'save-cel-url'
    - title: '_Load URL'
      event: 'load-cel-url'
    -
    - title: 'Load _CEL script'
      event: 'open-script'
    -
    - title: 'Go to _home'
      event: 'select-home'
    -
    - title: '_Preferences'
      event: 'gui-show-preferences'
    -
    - title: '_Quit'
      event: 'exit'

- title: '_Select'
  entries:
    - title: '_Info'
      event: 'gui-show-info'
      enabled: 'has-object-selected'
    - title: '_Edit'
      event: 'gui-show-editor'
      enabled: 'has-object-selected'
    - title: "More info"
      menu: extra-info
      enabled: 'has-object-selected'
    -
    - title: '_Go to'
      event: 'goto-selected'
      enabled: 'has-object-selected'
    - title: 'Go to f_ront'
      event: 'goto-front'
      enabled: 'has-object-selected'
    - title: 'Go to _surface'
      event: 'goto-surface'
      enabled: 'has-object-selected'
    -
    - title: '_Follow'
      event: 'follow-selected'
      enabled: 'has-object-selected'
    - title: 'S_ync'
      event: 'sync-selected'
      enabled: 'has-object-selected'
    -
    - title: '_Reset navigation'
      event: 'cancel'
      enabled: 'has-object-selected'
    -
    - title: "Orbiting bodies"
      menu: 'orbiting-bodies'
      enabled: 'has-object-selected'
    - title: "Orbits"
      menu: 'orbits'
      enabled: 'has-object-selected'

- title: '_Time'
  entries:
    - title: '_Increase rate 10x'
      event: 'accelerate-time-10'
    - title: 'I_ncrease rate 2x'
      event: 'accelerate-time-2'
    - title: '_Decrease rate 10x'
      event: 'slow-time-10'
    - title: 'D_ecrease rate 2x'
      event: 'slow-time-2'
    - title: '_Reverse time'
      event: 'invert-time'
    - title: '_Freeze time'
      event: 'toggle-freeze-time'
    - title: '_Set real time'
      event: 'set-real-time'
    -
    - title: 'Set _time...'
      event: 'gui-show-time-editor'
    - title: 'Set _current time'
      event: 'set-current-date'
    - title: 'Set _J2000 epoch'
      event: 'set-j2000-date'

- title: 'Camera'
  entries:
    - title: '_Mode'
      menu: 'select-camera-controller'
    -
    - title: '_Center on'
      event: 'center-selected'
      enabled: 'has-object-selected'
    #- title: 'Look _back'
    #  event: camera-look-back
    - title: '_Track'
      event: 'track-selected'
      enabled: 'has-object-selected'
    -
    - title: 'Zoom _in'
      event: 'zoom-in'
    - title: 'Zoom _out'
      event: 'zoom-out'
    - title: '_Reset Zoom'
      event: 'reset-zoom'
    -
    - title: '_Select ship'
      menu: 'select-ship'
    - title: '_Edit ship'
      event: 'gui-show-ship-editor'
      enabled: 'ship-editable'

- title: '_Render'
  entries:
    - title: '_Labels'
      entries:
        - title: '_Galaxies'
          state: 'label-galaxy-shown'
          event: 'toggle-label-galaxy'
        #- title: 'Globular'
        #  state: 'label-globular'
        #  event: 'toggle-label-globular'
        - title: '_Stars'
          state: 'label-star-shown'
          event: 'toggle-label-star'
        - title: '_Planets'
          state: 'label-planet-shown'
          event: 'toggle-label-planet'
        - title: '_Dwarf planets'
          state: 'label-dwarfplanet-shown'
          event: 'toggle-label-dwarfplanet'
        - title: '_Moons'
          state: 'label-moon-shown'
          event: 'toggle-label-moon'
        - title: 'M_inor Moons'
          state: 'label-minormoon-shown'
          event: 'toggle-label-minormoon'
        - title: 'L_ost Moons'
          state: 'label-lostmoon-shown'
          event: 'toggle-label-lostmoon'
        - title: 'C_omets'
          state: 'label-comet-shown'
          event: 'toggle-label-comet'
        - title: '_Asteroids'
          state: 'label-asteroid-shown'
          event: 'toggle-label-asteroid'
        - title: 'I_nterstellars'
          state: 'label-interstellar-shown'
          event: 'toggle-label-interstellar'
        - title: 'S_pacecrafts'
          state: 'label-spacecraft-shown'
          event: 'toggle-label-spacecraft'
        - title: '_Constellations'
          state: 'label-constellation-shown'
          event: 'toggle-label-constellation'
        #- title: 'Locations'
        #  state: 'label-location'
        #  event: 'toggl-label-location'
    - title: '_Orbits'
      entries:
        - title: 'All _orbits'
          state: 'show-orbits'
          event: 'toggle-orbits'
        -
        - title: '_Stars'
          state: 'orbit-star-shown'
          event: 'toggle-orbit-star'
        - title: '_Planets'
          state: 'orbit-planet-shown'
          event: 'toggle-orbit-planet'
        - title: '_Dwarf planets'
          state: 'orbit-dwarfplanet-shown'
          event: 'toggle-orbit-dwarfplanet'
        - title: '_Moons'
          state: 'orbit-moon-shown'
          event: 'toggle-orbit-moon'
        - title: 'M_inor moons'
          state: 'orbit-minormoon-shown'
          event: 'toggle-orbit-minormoon'
        - title: 'L_ost moons'
          state: 'orbit-lostmoon-shown'
          event: 'toggle-orbit-lostmoon'
        - title: '_Comets'
          state: 'orbit-comet-shown'
          event: 'toggle-orbit-comet'
        - title: '_Asteroids'
          state: 'orbit-asteroid-shown'
          event: 'toggle-orbit-asteroid'
        - title: 'I_nterstellars'
          state: 'orbit-interstellar-shown'
          event: 'toggle-orbit-interstellar'
        - title: 'S_pacecrafts'
          state: 'orbit-spacecraft-shown'
          event: 'toggle-orbit-spacecraft'
    - title: '_Bodies'
      entries:
        - title: '_Galaxies'
          state: 'galaxy-shown'
          event: 'toggle-body-class-galaxy'
    - title: 'O_ptions'
      entries:
        - title: '_Atmospheres'
          state: 'show-atmospheres'
          event: 'toggle-atmosphere'
        - title: '_Clouds'
          state: 'show-clouds'
          event: 'toggle-clouds'
          #- title: 'Shadows'
          #  event: 'toggle-shadows'
          #- title: 'Night sides'
          #  event: 'toggle-nightsides'
          #- title: 'Comet tails'
          #  event: 'toggle-comet-tails'
    - title: '_Grids'
      menu: grids
    - title: 'G_uides'
      menu: guides
    - title: '_3D'
      menu: stereo
    - title: '_Advanced'
      entries:
        - title: '_Decrease ambient'
          event: 'decrease-ambient'
        - title: '_Increase ambient'
          event: 'increase-ambient'
        -
        - title: 'Fewer _Stars Visible'
          event: 'decrease-limit-magnitude'
        - title: '_More Stars Visible'
          event: 'increase-limit-magnitude'
        -
        - title: '_Rotation axis'
          state: 'show-rotation-axis'
          event: 'toggle-rotation-axis'
        - title: 'Reference _frame'
          state: 'show-reference-axis'
          event: 'toggle-reference-axis'

- title: '_Window'
  entries:
    - title: 'Toggle _fullscreen'
      event: 'toggle-fullscreen'
    - title: 'Toggle _menubar'
      event: 'gui-toggle-menubar'
    - title: 'Toggle _HUD'
      event: 'toggle-hud'
    -
    - title: 'Save _screenshot'
      event: 'save-screenshot'
    - title: 'Save screenshot _without UI'
      event: 'save-screenshot-no-gui'
    - title: 'Set screenshots directory...'
      event: 'gui-show-select-screenshots'

- title: '_Debug'
  entries:
    - title: 'Toggle filled wireframe'
      event: 'debug-toggle-filled-wireframe'
    - title: 'Toggle wireframe'
      event: 'debug-toggle-wireframe'
    - title: "Show render buffers"
      event: 'debug-toggle-buffer-viewer'
    - title: 'Show shadow frustum'
      state: 'debug-shadow-frustum'
      event: 'debug-toggle-shadows-frustum'
    -
    - title: 'Shaders'
      entries:
        - title: 'Default'
          state: 'debug-shader-fragment-mode-default'
          event: 'debug-shader-fragment-mode-default'
        - title: 'Diffuse'
          state: 'debug-shader-fragment-mode-diffuse'
          event: 'debug-shader-fragment-mode-diffuse'
        - title: 'Normals'
          state: 'debug-shader-fragment-mode-normal'
          event: 'debug-shader-fragment-mode-normal'
        - title: 'Normal map'
          state: 'debug-shader-fragment-mode-normalmap'
          event: 'debug-shader-fragment-mode-normalmap'
        - title: 'Shadows'
          state: 'debug-shader-fragment-mode-shadows'
          event: 'debug-shader-fragment-mode-shadows'
        - title: 'Heightmap'
          state: 'debug-shader-fragment-mode-heightmap'
          event: 'debug-shader-fragment-mode-heightmap'
        - title: 'Color picking'
          state: 'debug-shader-fragment-mode-picking'
          event: 'debug-shader-fragment-mode-picking'
        - title: 'Ray hit'
          state: 'shader-debug-raymarching-canvas'
          event: 'debug-toggle-shader-raymarching-canvas'
        - title: 'Show slice'
          state: 'shader-debug-raymarching-slice'
          event: 'debug-toggle-shader-debug-raymarching_slice'
    - title: 'Instant movement'
      state: 'debug-jump'
      event: 'debug-toggle-jump'
    - title: 'Connect pstats'
      event: 'debug-connect-pstats'
    - title: 'Render info'
      entries:
        - title: 'Frame per second'
          state: 'display-render-info-fps'
          event: 'set-display-render-info-fps'
        - title: 'Render time'
          state: 'display-render-info-ms'
          event: 'set-display-render-info-ms'
        - title: 'None'
          state: 'display-render-info-none'
          event: 'set-display-render-info-none'
    -
    - title: 'Freeze LOD'
      state: 'debug-lod-freeze'
      event: 'debug-freeze-lod'
    - title: 'Dump LOD stats'
      event: 'debug-dump-objects-stats'
    - title: 'Dump LOD tree'
      event: 'debug-dump-objects-info'
    - title: 'Log LOD events'
      state: 'debug-lod-split-merge'
      event: 'debug-toggle-split-merge-log'
    - title: 'Show boundaries'
      state: 'shader-debug-coord'
      event: 'debug-toggle-shader-debug-coord'
    - title: 'Show LOD bounding boxes'
      state: 'debug-lod-show-bb'
      event: 'debug-toggle-bounding-boxes'
    - title: 'Show LOD culling frustum'
      state: 'debug-lod-frustum'
      event: 'debug-toggle-lod-frustum'
    -
    - title: 'Show octree stats'
      event: 'debug-dump-octree-stats'
    - title: 'Dump octree'
      event: 'debug-dump-octree'

- title: '_Help'
  entries:
    - title: 'User _guide'
      event: 'gui-show-help'
    -
    - title: '_Credits'
      event: 0
    - title: '_License'
      event: 'gui-show-license'
    -
    - title: '_About'
      event: 'gui-show-about'
