popup:
- title: '@over-name'
  visible: 'has-object-selected'
  event: 'center-selected'
-
- title: '_Info'
  visible: 'has-object-selected'
  event: 'gui-show-info'
- title: '_Goto'
  visible: 'has-object-selected'
  event: 'goto-selected'
- title: '_Follow'
  visible: 'has-object-selected'
  event: 'follow-selected'
- title: 'S_ync'
  visible: 'has-object-selected'
  event: 'sync-selected'
- title: "Surfaces"
  visible: 'has-object-selected'
  menu: over-surfaces
- title: "Orbiting bodies"
  visible: 'has-object-selected'
  menu: over-orbiting-bodies
- title: "Orbits"
  visible: 'has-object-selected'
  menu: over-orbits
- title: '_Edit'
  visible: 'has-object-selected'
  event: 'gui-show-editor'
- title: "More info"
  visible: 'has-object-selected'
  menu: over-extra-info
- visible: 'gui-menubar-hidden'
- title: "Show _menubar"
  event: 'gui-show-menubar'
  visible: 'gui-menubar-hidden'
