popup:
- title: '@select-name'
  visible: 'engine.selected'
  event: 'center-selected'
-
- title: '_Info'
  visible: 'engine.selected'
  event: 'gui-show-info'
- title: '_Goto'
  visible: 'engine.selected'
  event: 'goto-selected'
- title: '_Follow'
  visible: 'engine.selected'
  event: 'follow-selected'
- title: 'S_ync'
  visible: 'engine.selected'
  event: 'sync-selected'
- title: "Surfaces"
  visible: 'engine.selected'
  menu: surfaces
- title: "Orbiting bodies"
  visible: 'engine.selected'
  menu: orbiting-bodies
- title: "Orbits"
  visible: 'engine.selected'
  menu: orbits
- title: '_Edit'
  visible: 'engine.selected'
  event: 'gui-show-editor'
- title: "More info"
  visible: 'engine.selected'
  menu: extra-info
- visible: 'not gui.menubar_shown'
- title: "Show _menubar"
  event: 'gui-show-menubar'
  visible: 'not gui.menubar_shown'
