exit: control-q
gui-search-object: enter
escape-dispatch: escape
toggle-fullscreen: alt-enter
zoom-in: ","
zoom-out: "."
reset-zoom: control-r
gui-toggle-menubar: control-m
gui-show-preferences: control-p
gui-show-editor: control-e
gui-show-info: f1
gui-show-help: shift-f1
debug-connect-pstats: f2
debug-toggle-filled-wireframe: f3
debug-toggle-wireframe: shift-f3
toggle-hdr: f4
debug-toggle-buffer-viewer: f5
debug-dump-octree-stats: f7
debug-dump-octree: shift-f7
debug-freeze-lod: f8
debug-dump-objects-stats: shift-f8
debug-dump-objects-info: shift-control-f8
debug-toggle-split-merge-log: control-f8
debug-toggle-shader-debug-coord: f9
debug-toggle-bounding-boxes: shift-f9
debug-toggle-lod-frustum: control-f9
debug-toggle-shadows-frustum: shift-control-f9
save-screenshot: f10
save-screenshot-no-gui: shift-f10
debug-scene-ls: f11
debug-scene-explore: control-f11
debug-scene-analyze: f12
debug-print-tasks: shift-f12
follow-selected: f
sync-selected: y
track-selected: t
control-selected: control-t
goto-front: d
goto-illuminated-front: shift-d
goto-selected: g
center-selected: c
debug-toggle-jump: control-j
goto-north: shift-n
goto-south: shift-s
goto-meridian: shift-r
align-ecliptic: shift-e
align-equatorial: shift-q
goto-surface: control-g
select-home: h
save-cel-url: control-c
load-cel-url: control-v
open-script: control-o
set-j2000-date: shift-j
set-current-date: "!"
accelerate-time-10: l
accelerate-time-2: shift-l
slow-time-10: k
slow-time-2: shift-k
invert-time: j
toggle-freeze-time: space
set-real-time: "\\"
decrease-ambient: "{"
increase-ambient: "}"
decrease-limit-magnitude: "["
increase-limit-magnitude: "]"
toggle-atmosphere: control-a
toggle-rotation-axis: shift-a
toggle-reference-axis: shift-control-r
toggle-constellations-boundaries: control-b
toggle-clouds: i
toggle-orbits: o
toggle-body-class-galaxy: u
toggle-equatorial-grid: ;
toggle-ecliptic-grid: ":"
toggle-asterisms: /
toggle-orbit-star: shift-control-b
toggle-orbit-planet: shift-control-p
toggle-orbit-dwarfplanet: shift-control-d
toggle-orbit-moon: shift-control-m
toggle-orbit-minormoon: shift-control-o
toggle-orbit-comet: shift-control-c
toggle-orbit-asteroid: shift-control-a
toggle-orbit-spacecraft: shift-control-s
toggle-label-galaxy: e
toggle-label-star: b
toggle-label-planet: p
toggle-label-dwarfplanet: shift-p
toggle-label-moon: m
toggle-label-minormoon: shift-m
toggle-label-comet: shift-w
toggle-label-asteroid: w
toggle-label-spacecraft: n
toggle-label-constellation: "="
toggle-hud: v
select-object-0: 0
select-object-1: 1
select-object-2: 2
select-object-3: 3
select-object-4: 4
select-object-5: 5
select-object-6: 6
select-object-7: 7
select-object-8: 8
select-object-9: 9
debug-print-info: shift-h
toggle-fly-mode: shift-y
