name: build
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y build-essential pkg-config fakeroot python3-dev python3-setuptools software-properties-common libpng-dev libjpeg-dev libtiff-dev zlib1g-dev libssl-dev libx11-dev libgl1-mesa-dev libxrandr-dev libxxf86dga-dev libxcursor-dev bison flex libfreetype6-dev libvorbis-dev libeigen3-dev libopenal-dev libode-dev libbullet-dev nvidia-cg-toolkit libgtk2.0-dev libassimp-dev libopenexr-dev libopusfile0 libsquish0
        sudo python3 -m pip install --upgrade pip
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 87828F5B 80AD5260 49F9BF71 BFC01641E375BC9D
        sudo add-apt-repository 'deb https://archive.panda3d.org/ubuntu/ focal-dev main'
        sudo apt-get update
        sudo apt-get install panda3d1.11
    - name: Build app
      run: |
        echo "--extra-index-url https://archive.panda3d.org/simple" > requirements-tmp.txt
        echo "panda3d>=1.11.0.dev0" >> requirements-tmp.txt
        cat requirements.txt >> requirements-tmp.txt
        make build SOURCE_OPTIONS="--optimize 3"
        python3 setup.py bdist_apps -p manylinux1_x86_64 -r requirements-tmp.txt
        python3 setup.py bdist_apps -p manylinux1_i686 -r requirements-tmp.txt
    - name: Test binary
      run: |
        cd build/manylinux1_x86_64
        ./cosmonium --test-start
    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: linux-logs
        path: ~/.local/share/cosmonium/output.log
    - name: 'Upload development build'
      if: false && github.ref == 'refs/heads/develop'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-linux"
        prerelease: true
        title: "Linux Development Build"
        files: dist/*

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panda3d>=1.10.7
    - name: Build binary
      run: |
        echo "panda3d" > requirements-tmp.txt
        cat requirements.txt >> requirements-tmp.txt
        python setup.py bdist_apps -p macosx_10_9_x86_64 -r requirements-tmp.txt
    - name: Test binary
      run: |
        cd build/macosx_10_9_x86_64/cosmonium.app/Contents/MacOS
        ./cosmonium --test-start
    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: macos-logs
        path: ~/Documents/cosmonium/output.log
    - name: 'Upload development build'
      if: false && github.ref == 'refs/heads/develop'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-macos"
        prerelease: true
        title: "MacOS Development Build"
        files: dist/*

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panda3d>=1.10.7
    - name: Build binary
      run: |
        echo "panda3d" > requirements-tmp.txt
        cat requirements.txt >> requirements-tmp.txt
        python setup.py bdist_apps -p win_amd64,win32 -r requirements-tmp.txt
    - name: Test binary
      run: |
        cd build/win_amd64
        & ./cosmonium.exe --% --test-start
        cd ../win32
        & ./cosmonium.exe --% --test-start
    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: windows-logs
        path: ~/AppData/Local/cosmonium/output.log
    - name: 'Upload development build'
      if: false && github.ref == 'refs/heads/develop'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-windows"
        prerelease: true
        title: "Windows Development Build"
        files: build/*.exe
